# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/139/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/139/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luc/Projects/CCVM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luc/Projects/CCVM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/139/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/139/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luc/Projects/CCVM/CMakeFiles /home/luc/Projects/CCVM/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luc/Projects/CCVM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/luc/Projects/CCVM/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ccvm

# Build rule for target.
ccvm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ccvm
.PHONY : ccvm

# fast build rule for target.
ccvm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/build
.PHONY : ccvm/fast

sources/CCVM.o: sources/CCVM.c.o

.PHONY : sources/CCVM.o

# target to build an object file
sources/CCVM.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/CCVM.c.o
.PHONY : sources/CCVM.c.o

sources/CCVM.i: sources/CCVM.c.i

.PHONY : sources/CCVM.i

# target to preprocess a source file
sources/CCVM.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/CCVM.c.i
.PHONY : sources/CCVM.c.i

sources/CCVM.s: sources/CCVM.c.s

.PHONY : sources/CCVM.s

# target to generate assembly for a file
sources/CCVM.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/CCVM.c.s
.PHONY : sources/CCVM.c.s

sources/flags.o: sources/flags.c.o

.PHONY : sources/flags.o

# target to build an object file
sources/flags.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/flags.c.o
.PHONY : sources/flags.c.o

sources/flags.i: sources/flags.c.i

.PHONY : sources/flags.i

# target to preprocess a source file
sources/flags.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/flags.c.i
.PHONY : sources/flags.c.i

sources/flags.s: sources/flags.c.s

.PHONY : sources/flags.s

# target to generate assembly for a file
sources/flags.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/flags.c.s
.PHONY : sources/flags.c.s

sources/instructionset.o: sources/instructionset.c.o

.PHONY : sources/instructionset.o

# target to build an object file
sources/instructionset.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/instructionset.c.o
.PHONY : sources/instructionset.c.o

sources/instructionset.i: sources/instructionset.c.i

.PHONY : sources/instructionset.i

# target to preprocess a source file
sources/instructionset.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/instructionset.c.i
.PHONY : sources/instructionset.c.i

sources/instructionset.s: sources/instructionset.c.s

.PHONY : sources/instructionset.s

# target to generate assembly for a file
sources/instructionset.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/instructionset.c.s
.PHONY : sources/instructionset.c.s

sources/main.o: sources/main.c.o

.PHONY : sources/main.o

# target to build an object file
sources/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/main.c.o
.PHONY : sources/main.c.o

sources/main.i: sources/main.c.i

.PHONY : sources/main.i

# target to preprocess a source file
sources/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/main.c.i
.PHONY : sources/main.c.i

sources/main.s: sources/main.c.s

.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/main.c.s
.PHONY : sources/main.c.s

sources/ram.o: sources/ram.c.o

.PHONY : sources/ram.o

# target to build an object file
sources/ram.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/ram.c.o
.PHONY : sources/ram.c.o

sources/ram.i: sources/ram.c.i

.PHONY : sources/ram.i

# target to preprocess a source file
sources/ram.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/ram.c.i
.PHONY : sources/ram.c.i

sources/ram.s: sources/ram.c.s

.PHONY : sources/ram.s

# target to generate assembly for a file
sources/ram.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/ram.c.s
.PHONY : sources/ram.c.s

sources/stack.o: sources/stack.c.o

.PHONY : sources/stack.o

# target to build an object file
sources/stack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/stack.c.o
.PHONY : sources/stack.c.o

sources/stack.i: sources/stack.c.i

.PHONY : sources/stack.i

# target to preprocess a source file
sources/stack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/stack.c.i
.PHONY : sources/stack.c.i

sources/stack.s: sources/stack.c.s

.PHONY : sources/stack.s

# target to generate assembly for a file
sources/stack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ccvm.dir/build.make CMakeFiles/ccvm.dir/sources/stack.c.s
.PHONY : sources/stack.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ccvm"
	@echo "... sources/CCVM.o"
	@echo "... sources/CCVM.i"
	@echo "... sources/CCVM.s"
	@echo "... sources/flags.o"
	@echo "... sources/flags.i"
	@echo "... sources/flags.s"
	@echo "... sources/instructionset.o"
	@echo "... sources/instructionset.i"
	@echo "... sources/instructionset.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
	@echo "... sources/ram.o"
	@echo "... sources/ram.i"
	@echo "... sources/ram.s"
	@echo "... sources/stack.o"
	@echo "... sources/stack.i"
	@echo "... sources/stack.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/luc/Projects/CCVM/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

